-- Completa el plan de ISI con lo que tenia la app Django "ProjectUTN"
-- (backend/db.sqlite3 y frontend/src/views/estado/materias.json):
-- electivas y Practica Supervisada, sus correlativas, links a los programas
-- analiticos y las comisiones con sus horarios.
-- +goose Up
-- +goose StatementBegin
insert into materia (codigo, nombre, area, bloque, nivel, cuatrimestre_id, carga_horaria, tipo, horas, programa)
select v.codigo, v.nombre, v.area, v.bloque, v.nivel, cu.id, v.carga_horaria, v.tipo, v.horas, ''
from (values
    ('isi-qca', 'Química para Ingeniería en Sistemas de Información', 'Electivas', 'Ciencias y Tecnologías Complementarias', 2, '2C', 2, 'Electiva', 72),
    ('isi-sdr', 'Sist. Rep. para Ingeniería en Sistemas de Información', 'Electivas', 'Ciencias y Tecnologías Complementarias', 2, '2C', 2, 'Electiva', 72),
    ('isi-ctda', 'Complejidad y Técnicas de Diseño de Algoritmos', 'Electivas', 'Ciencias y Tecnologías Complementarias', 3, '1C', 3, 'Electiva', 72),
    ('isi-planif', 'Planificación', 'Electivas', 'Ciencias y Tecnologías Complementarias', 3, '1C', 3, 'Electiva', 72),
    ('isi-sgbd', 'Sistemas de Gestión de Base de Datos', 'Electivas', 'Ciencias y Tecnologías Complementarias', 3, '2C', 3, 'Electiva', 72),
    ('isi-aacs', 'Aspectos Avanzados de Calidad de Software', 'Electivas', 'Ciencias y Tecnologías Complementarias', 4, '2C', 3, 'Electiva', 72),
    ('isi-agavz', 'Agilidad Avanzada', 'Electivas', 'Ciencias y Tecnologías Complementarias', 4, '2C', 3, 'Electiva', 72),
    ('isi-gis', 'Sistemas de Información Geográficos', 'Electivas', 'Ciencias y Tecnologías Complementarias', 4, '2C', 3, 'Electiva', 72),
    ('isi-aaari', 'Aspectos Avanzados de Redes de Información', 'Electivas', 'Ciencias y Tecnologías Complementarias', 5, '2C', 3, 'Electiva', 72),
    ('isi-ade', 'Análisis de Datos Empresariales', 'Electivas', 'Ciencias y Tecnologías Complementarias', 5, '1C', 3, 'Electiva', 72),
    ('isi-aif', 'Auditoría e Informática Forense', 'Electivas', 'Ciencias y Tecnologías Complementarias', 5, '2C', 4, 'Electiva', 96),
    ('isi-devops', 'DevOps - Cultura, Herramientas y Procesos', 'Electivas', 'Ciencias y Tecnologías Complementarias', 5, '2C', 4, 'Electiva', 96),
    ('isi-fcs', 'Fundamentos de Ciberseguridad', 'Electivas', 'Ciencias y Tecnologías Complementarias', 5, '2C', 3, 'Electiva', 72),
    ('isi-femp', 'Formación de Emprendedores', 'Electivas', 'Ciencias y Tecnologías Complementarias', 5, '1C', 4, 'Electiva', 96),
    ('isi-ps', 'Práctica Supervisada', 'Práctica Supervisada', 'Práctica Profesional Supervisada', 5, 'Anual', 0, 'Obligatoria', 96)
) as v(codigo, nombre, area, bloque, nivel, cuatrimestre, carga_horaria, tipo, horas)
join cuatrimestre cu on cu.nombre = v.cuatrimestre
on conflict (codigo) do nothing;

insert into materiasPorcarrera (carrera_id, materia_id)
select c.id, m.id from carrera c, materia m
where c.nombre = 'Ingeniería en Sistemas de Información' and m.codigo like 'isi-%'
on conflict (carrera_id, materia_id) do nothing;

insert into correlativa (materia_id, requiere_id, tipo)
select m.id, r.id, v.tipo
from (values
    ('isi-aaari', 'isi-ads', 'aprobada'),
    ('isi-aaari', 'isi-com', 'aprobada'),
    ('isi-aaari', 'isi-f2', 'regular'),
    ('isi-aaari', 'isi-rdd', 'regular'),
    ('isi-aacs', 'isi-dsi', 'regular'),
    ('isi-aacs', 'isi-iycs', 'regular'),
    ('isi-ade', 'isi-bdd', 'aprobada'),
    ('isi-ade', 'isi-pye', 'aprobada'),
    ('isi-ade', 'isi-sim', 'regular'),
    ('isi-admsi', 'isi-ads', 'aprobada'),
    ('isi-admsi', 'isi-dsi', 'regular'),
    ('isi-admsi', 'isi-eco', 'regular'),
    ('isi-ads', 'isi-aed', 'regular'),
    ('isi-ads', 'isi-sposn', 'regular'),
    ('isi-agavz', 'isi-dsi', 'aprobada'),
    ('isi-agavz', 'isi-dsw', 'aprobada'),
    ('isi-agavz', 'isi-iycs', 'regular'),
    ('isi-aif', 'isi-dsi', 'aprobada'),
    ('isi-aif', 'isi-dsw', 'aprobada'),
    ('isi-aif', 'isi-iycs', 'regular'),
    ('isi-aif', 'isi-leg', 'aprobada'),
    ('isi-aif', 'isi-ssi', 'regular'),
    ('isi-am2', 'isi-am1', 'regular'),
    ('isi-am2', 'isi-ayga', 'regular'),
    ('isi-an', 'isi-am1', 'aprobada'),
    ('isi-an', 'isi-am2', 'aprobada'),
    ('isi-an', 'isi-ayga', 'aprobada'),
    ('isi-bdd', 'isi-ads', 'regular'),
    ('isi-bdd', 'isi-aed', 'aprobada'),
    ('isi-bdd', 'isi-led', 'aprobada'),
    ('isi-bdd', 'isi-ssl', 'regular'),
    ('isi-cdd', 'isi-bdd', 'aprobada'),
    ('isi-cdd', 'isi-pye', 'aprobada'),
    ('isi-cdd', 'isi-sim', 'regular'),
    ('isi-com', 'isi-adc', 'aprobada'),
    ('isi-com', 'isi-f1', 'aprobada'),
    ('isi-ctda', 'isi-aed', 'aprobada'),
    ('isi-ctda', 'isi-pdp', 'regular'),
    ('isi-devops', 'isi-dsw', 'regular'),
    ('isi-devops', 'isi-iycs', 'regular'),
    ('isi-devops', 'isi-rdd', 'regular'),
    ('isi-devops', 'isi-so', 'aprobada'),
    ('isi-dsi', 'isi-ads', 'regular'),
    ('isi-dsi', 'isi-aed', 'aprobada'),
    ('isi-dsi', 'isi-ing1', 'aprobada'),
    ('isi-dsi', 'isi-pdp', 'regular'),
    ('isi-dsi', 'isi-sposn', 'aprobada'),
    ('isi-dsw', 'isi-ads', 'regular'),
    ('isi-dsw', 'isi-aed', 'aprobada'),
    ('isi-dsw', 'isi-led', 'aprobada'),
    ('isi-dsw', 'isi-pdp', 'regular'),
    ('isi-eco', 'isi-am1', 'aprobada'),
    ('isi-eco', 'isi-ayga', 'aprobada'),
    ('isi-f2', 'isi-am1', 'regular'),
    ('isi-f2', 'isi-f1', 'regular'),
    ('isi-fcs', 'isi-com', 'regular'),
    ('isi-fcs', 'isi-dsi', 'aprobada'),
    ('isi-fcs', 'isi-rdd', 'aprobada'),
    ('isi-femp', 'isi-admsi', 'regular'),
    ('isi-femp', 'isi-eco', 'aprobada'),
    ('isi-gg', 'isi-admsi', 'regular'),
    ('isi-gg', 'isi-eco', 'aprobada'),
    ('isi-gg', 'isi-leg', 'regular'),
    ('isi-gis', 'isi-ads', 'aprobada'),
    ('isi-gis', 'isi-bdd', 'regular'),
    ('isi-gis', 'isi-dsi', 'regular'),
    ('isi-ia', 'isi-an', 'aprobada'),
    ('isi-ia', 'isi-pye', 'aprobada'),
    ('isi-ia', 'isi-sim', 'regular'),
    ('isi-ing2', 'isi-ing1', 'regular'),
    ('isi-io', 'isi-an', 'regular'),
    ('isi-io', 'isi-pye', 'regular'),
    ('isi-iycs', 'isi-bdd', 'regular'),
    ('isi-iycs', 'isi-dsi', 'regular'),
    ('isi-iycs', 'isi-dsw', 'regular'),
    ('isi-iycs', 'isi-pdp', 'aprobada'),
    ('isi-iycs', 'isi-ssl', 'aprobada'),
    ('isi-leg', 'isi-iys', 'regular'),
    ('isi-pdp', 'isi-aed', 'regular'),
    ('isi-pdp', 'isi-led', 'regular'),
    ('isi-pf', 'isi-admsi', 'regular'),
    ('isi-pf', 'isi-dsi', 'aprobada'),
    ('isi-pf', 'isi-dsw', 'aprobada'),
    ('isi-pf', 'isi-ing2', 'aprobada'),
    ('isi-pf', 'isi-iycs', 'regular'),
    ('isi-pf', 'isi-rdd', 'regular'),
    ('isi-planif', 'isi-ads', 'regular'),
    ('isi-planif', 'isi-eco', 'regular'),
    ('isi-planif', 'isi-sposn', 'aprobada'),
    ('isi-pye', 'isi-am1', 'regular'),
    ('isi-pye', 'isi-ayga', 'regular'),
    ('isi-rdd', 'isi-com', 'regular'),
    ('isi-rdd', 'isi-so', 'regular'),
    ('isi-sg', 'isi-dsi', 'aprobada'),
    ('isi-sg', 'isi-eco', 'regular'),
    ('isi-sg', 'isi-io', 'regular'),
    ('isi-sgbd', 'isi-bdd', 'regular'),
    ('isi-sim', 'isi-am2', 'aprobada'),
    ('isi-sim', 'isi-pye', 'regular'),
    ('isi-so', 'isi-adc', 'regular'),
    ('isi-ssi', 'isi-admsi', 'regular'),
    ('isi-ssi', 'isi-com', 'aprobada'),
    ('isi-ssi', 'isi-dsw', 'aprobada'),
    ('isi-ssi', 'isi-rdd', 'regular'),
    ('isi-ssl', 'isi-aed', 'regular'),
    ('isi-ssl', 'isi-led', 'regular'),
    ('isi-tpla', 'isi-am2', 'aprobada'),
    ('isi-tpla', 'isi-an', 'regular'),
    ('isi-tpla', 'isi-f2', 'regular')
) as v(materia, requiere, tipo)
join materia m on m.codigo = v.materia
join materia r on r.codigo = v.requiere
on conflict (materia_id, requiere_id) do nothing;

update materia m set programa = v.programa
from (values
    ('isi-aaari', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13936.pdf'),
    ('isi-aacs', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13935.pdf'),
    ('isi-adc', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13734.pdf'),
    ('isi-ade', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13933.pdf'),
    ('isi-admsi', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13746.pdf'),
    ('isi-ads', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13736.pdf'),
    ('isi-aed', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13733.pdf'),
    ('isi-agavz', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13932.pdf'),
    ('isi-aif', 'https://drive.google.com/file/d/1pY8V_UgdpJ-QgY9BmY7uNIcrJvixz6Ay/view?usp=drive_link'),
    ('isi-am1', 'https://www.frre.utn.edu.ar/iq/clean/files/get/item/7373'),
    ('isi-am2', 'https://www.frre.utn.edu.ar/iq/clean/files/get/item/7373'),
    ('isi-an', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13744.pdf'),
    ('isi-ayga', 'https://www.frre.utn.edu.ar/iq/clean/files/get/item/7373'),
    ('isi-bdd', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13742.pdf'),
    ('isi-cdd', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13754.pdf'),
    ('isi-com', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13741.pdf'),
    ('isi-ctda', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13938.pdf'),
    ('isi-devops', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13939.pdf'),
    ('isi-dsi', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13740.pdf'),
    ('isi-dsw', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13743.pdf'),
    ('isi-eco', 'https://www.frre.utn.edu.ar/iq/clean/files/get/item/7430'),
    ('isi-f1', 'https://www.frre.utn.edu.ar/iq/clean/files/get/item/7373'),
    ('isi-f2', 'https://www.frre.utn.edu.ar/iq/clean/files/get/item/7373'),
    ('isi-fcs', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13941.pdf'),
    ('isi-femp', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13940.pdf'),
    ('isi-gg', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13752.pdf'),
    ('isi-gis', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13943.pdf'),
    ('isi-ia', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13753.pdf'),
    ('isi-ing1', 'https://www.frre.utn.edu.ar/iq/clean/files/get/item/7373'),
    ('isi-ing2', 'https://www.frre.utn.edu.ar/iq/clean/files/get/item/7373'),
    ('isi-io', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13747.pdf'),
    ('isi-iycs', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13750.pdf'),
    ('isi-iys', 'https://www.frre.utn.edu.ar/iq/clean/files/get/item/7373'),
    ('isi-led', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13732.pdf'),
    ('isi-leg', 'https://www.frre.utn.edu.ar/iq/clean/files/get/item/7442'),
    ('isi-pdp', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13739.pdf'),
    ('isi-pf', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13756.pdf'),
    ('isi-planif', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13942.pdf'),
    ('isi-pye', 'https://www.frre.utn.edu.ar/iq/clean/files/get/item/7429'),
    ('isi-qca', 'https://www.frre.utn.edu.ar/iq/clean/files/get/item/7443'),
    ('isi-rdd', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13745.pdf'),
    ('isi-sdr', 'https://www.frre.utn.edu.ar/iq/clean/files/get/item/7441'),
    ('isi-sg', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13751.pdf'),
    ('isi-sgbd', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13931.pdf'),
    ('isi-sim', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13748.pdf'),
    ('isi-so', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13738.pdf'),
    ('isi-sposn', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13735.pdf'),
    ('isi-ssi', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13755.pdf'),
    ('isi-ssl', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13737.pdf'),
    ('isi-tpla', 'https://www.frre.utn.edu.ar/isi/clean/files/get/item/13749.pdf')
) as v(codigo, programa)
where m.codigo = v.codigo and m.programa = '';

alter table comision add column if not exists cuatrimestre text not null default '';
alter table comision add constraint comision_unica unique (materia_id, codigo);
alter table comision drop constraint if exists fk_materia;
alter table comision add constraint fk_materia foreign key (materia_id) references materia(id) on delete cascade;
alter table horario drop constraint if exists fk_comision;
alter table horario add constraint fk_comision foreign key (comision_id) references comision(id) on delete cascade;

insert into comision (codigo, cuatrimestre, materia_id)
select v.codigo, v.cuatrimestre, m.id
from (values
    ('K2.1', 'Anual', 'isi-adc'),
    ('K2.2', 'Anual', 'isi-adc'),
    ('K2.4', '1C', 'isi-adc'),
    ('K5.1', '1C', 'isi-ade'),
    ('K4.1', 'Anual', 'isi-admsi'),
    ('K2.1', 'Anual', 'isi-ads'),
    ('K2.2', 'Anual', 'isi-ads'),
    ('K1.1', 'Anual', 'isi-aed'),
    ('K1.2', 'Anual', 'isi-aed'),
    ('K1.3', 'Anual', 'isi-aed'),
    ('K1.4', 'Anual', 'isi-aed'),
    ('K1.5', 'Anual', 'isi-aed'),
    ('K1.1', 'Anual', 'isi-am1'),
    ('K1.2', 'Anual', 'isi-am1'),
    ('K1.3', 'Anual', 'isi-am1'),
    ('K1.4', 'Anual', 'isi-am1'),
    ('K1.5', 'Anual', 'isi-am1'),
    ('K2.1', 'Anual', 'isi-am2'),
    ('K2.2', 'Anual', 'isi-am2'),
    ('K1.1', 'Anual', 'isi-ayga'),
    ('K1.1', '1C', 'isi-ayga'),
    ('K1.1', '1C', 'isi-ayga'),
    ('K1.2', 'Anual', 'isi-ayga'),
    ('K1.3', 'Anual', 'isi-ayga'),
    ('K1.4', 'Anual', 'isi-ayga'),
    ('K1.5', 'Anual', 'isi-ayga'),
    ('K3.1', '1C', 'isi-bdd'),
    ('K3.1', '1C', 'isi-com'),
    ('K3.1', '1C', 'isi-ctda'),
    ('K3.1', 'Anual', 'isi-dsi'),
    ('K3.1', '1C', 'isi-eco'),
    ('K1.1', 'Anual', 'isi-f1'),
    ('K1.2', 'Anual', 'isi-f1'),
    ('K1.3', 'Anual', 'isi-f1'),
    ('K1.4', 'Anual', 'isi-f1'),
    ('K1.5', 'Anual', 'isi-f1'),
    ('K2.1', '1C', 'isi-f2'),
    ('K2.2', '1C', 'isi-f2'),
    ('K5.1', '1C', 'isi-femp'),
    ('K5.1', '1C', 'isi-gg'),
    ('K1.1', '2C', 'isi-ing1'),
    ('K1.2', '2C', 'isi-ing1'),
    ('K1.3', '2C', 'isi-ing1'),
    ('K1.4', '2C', 'isi-ing1'),
    ('K1.5', '2C', 'isi-ing1'),
    ('K4.1', '1C', 'isi-io'),
    ('K4.1', '1C', 'isi-iycs'),
    ('K2.1', '1C', 'isi-iys'),
    ('K2.2', '1C', 'isi-iys'),
    ('K1.1', '1C', 'isi-led'),
    ('K1.2', '1C', 'isi-led'),
    ('K1.3', '1C', 'isi-led'),
    ('K1.4', '1C', 'isi-led'),
    ('K1.5', '1C', 'isi-led'),
    ('K4.1', '1C', 'isi-leg'),
    ('K5.1', 'Anual', 'isi-pf'),
    ('K3.1', '1C', 'isi-planif'),
    ('K5.1', 'Anual', 'isi-ps'),
    ('K5.1', '1C', 'isi-sg'),
    ('K4.1', '1C', 'isi-sim'),
    ('K1.1', '2C', 'isi-sposn'),
    ('K1.2', '2C', 'isi-sposn'),
    ('K1.3', '2C', 'isi-sposn'),
    ('K1.4', '2C', 'isi-sposn'),
    ('K1.5', '2C', 'isi-sposn'),
    ('K5.1', '1C', 'isi-ssi'),
    ('K2.1', '1C', 'isi-ssl'),
    ('K2.2', '1C', 'isi-ssl')
) as v(codigo, cuatrimestre, materia)
join materia m on m.codigo = v.materia
on conflict (materia_id, codigo) do nothing;

insert into horario (comision_id, dia_id, hora_inicio, hora_fin)
select co.id, d.id, v.hora_inicio::time, v.hora_fin::time
from (values
    ('isi-adc', 'K2.1', 'Lunes', '17:20', '20:25'),
    ('isi-adc', 'K2.1', 'Martes', '12:45', '15:45'),
    ('isi-adc', 'K2.2', 'Lunes', '19:40', '22:45'),
    ('isi-adc', 'K2.2', 'Jueves', '13:30', '16:35'),
    ('isi-adc', 'K2.4', 'Miércoles', '08:30', '11:40'),
    ('isi-adc', 'K2.4', 'Viernes', '10:10', '13:10'),
    ('isi-ade', 'K5.1', 'Miércoles', '18:10', '22:45'),
    ('isi-admsi', 'K4.1', 'Miércoles', '17:20', '22:00'),
    ('isi-ads', 'K2.1', 'Miércoles', '15:50', '18:05'),
    ('isi-ads', 'K2.1', 'Viernes', '15:50', '18:05'),
    ('isi-ads', 'K2.2', 'Miércoles', '18:10', '20:25'),
    ('isi-ads', 'K2.2', 'Viernes', '18:10', '20:25'),
    ('isi-aed', 'K1.1', 'Martes', '10:55', '12:25'),
    ('isi-aed', 'K1.1', 'Viernes', '10:10', '12:25'),
    ('isi-aed', 'K1.2', 'Lunes', '10:55', '12:25'),
    ('isi-aed', 'K1.2', 'Viernes', '07:45', '10:00'),
    ('isi-aed', 'K1.3', 'Miércoles', '15:50', '18:05'),
    ('isi-aed', 'K1.3', 'Viernes', '16:35', '18:05'),
    ('isi-aed', 'K1.4', 'Lunes', '20:30', '22:00'),
    ('isi-aed', 'K1.4', 'Miércoles', '18:10', '20:25'),
    ('isi-aed', 'K1.5', 'Miércoles', '15:50', '18:05'),
    ('isi-aed', 'K1.5', 'Viernes', '16:35', '18:05'),
    ('isi-am1', 'K1.1', 'Lunes', '10:10', '12:25'),
    ('isi-am1', 'K1.1', 'Martes', '07:45', '09:15'),
    ('isi-am1', 'K1.2', 'Miércoles', '10:10', '12:25'),
    ('isi-am1', 'K1.2', 'Jueves', '10:10', '11:40'),
    ('isi-am1', 'K1.3', 'Lunes', '13:30', '17:20'),
    ('isi-am1', 'K1.4', 'Martes', '18:10', '22:00'),
    ('isi-am1', 'K1.5', 'Lunes', '13:30', '17:20'),
    ('isi-am2', 'K2.1', 'Lunes', '15:50', '17:20'),
    ('isi-am2', 'K2.1', 'Martes', '15:50', '18:05'),
    ('isi-am2', 'K2.2', 'Martes', '18:10', '22:00'),
    ('isi-ayga', 'K1.1', 'Martes', '09:15', '10:55'),
    ('isi-ayga', 'K1.1', 'Jueves', '07:45', '10:00'),
    ('isi-ayga', 'K1.2', 'Martes', '10:10', '11:40'),
    ('isi-ayga', 'K1.2', 'Miércoles', '07:45', '10:00'),
    ('isi-ayga', 'K1.3', 'Martes', '13:30', '15:45'),
    ('isi-ayga', 'K1.3', 'Jueves', '14:15', '15:45'),
    ('isi-ayga', 'K1.4', 'Jueves', '18:10', '22:00'),
    ('isi-ayga', 'K1.5', 'Martes', '13:30', '15:45'),
    ('isi-ayga', 'K1.5', 'Jueves', '14:15', '15:45'),
    ('isi-bdd', 'K3.1', 'Lunes', '18:10', '22:45'),
    ('isi-bdd', 'K3.1', 'Jueves', '16:35', '18:05'),
    ('isi-com', 'K3.1', 'Martes', '18:10', '21:15'),
    ('isi-com', 'K3.1', 'Viernes', '18:55', '22:00'),
    ('isi-ctda', 'K3.1', 'Lunes', '15:50', '18:05'),
    ('isi-ctda', 'K3.1', 'Miércoles', '15:50', '18:05'),
    ('isi-dsi', 'K3.1', 'Miércoles', '18:10', '22:45'),
    ('isi-eco', 'K3.1', 'Jueves', '18:10', '22:45'),
    ('isi-f1', 'K1.1', 'Miércoles', '07:45', '10:55'),
    ('isi-f1', 'K1.2', 'Lunes', '07:45', '10:55'),
    ('isi-f1', 'K1.3', 'Miércoles', '10:10', '13:10'),
    ('isi-f1', 'K1.4', 'Jueves', '15:00', '18:05'),
    ('isi-f1', 'K1.5', 'Lunes', '18:10', '21:15'),
    ('isi-f2', 'K2.1', 'Miércoles', '18:10', '20:25'),
    ('isi-f2', 'K2.1', 'Jueves', '18:10', '22:00'),
    ('isi-f2', 'K2.1', 'Viernes', '18:10', '19:40'),
    ('isi-f2', 'K2.2', 'Martes', '13:30', '15:45'),
    ('isi-f2', 'K2.2', 'Miércoles', '16:35', '18:05'),
    ('isi-f2', 'K2.2', 'Viernes', '13:30', '17:20'),
    ('isi-femp', 'K5.1', 'Sábado', '07:45', '12:25'),
    ('isi-gg', 'K5.1', 'Lunes', '20:30', '22:45'),
    ('isi-gg', 'K5.1', 'Viernes', '20:30', '22:45'),
    ('isi-ing1', 'K1.1', 'Martes', '17:20', '20:25'),
    ('isi-ing1', 'K1.2', 'Martes', '17:20', '20:25'),
    ('isi-ing1', 'K1.3', 'Martes', '07:45', '10:55'),
    ('isi-ing1', 'K1.4', 'Martes', '07:45', '10:55'),
    ('isi-io', 'K4.1', 'Jueves', '18:55', '22:00'),
    ('isi-io', 'K4.1', 'Viernes', '18:55', '22:00'),
    ('isi-iycs', 'K4.1', 'Martes', '20:30', '22:00'),
    ('isi-iycs', 'K4.1', 'Jueves', '15:50', '18:55'),
    ('isi-iys', 'K2.1', 'Lunes', '12:45', '15:45'),
    ('isi-iys', 'K2.2', 'Lunes', '12:45', '15:45'),
    ('isi-led', 'K1.1', 'Jueves', '10:10', '12:25'),
    ('isi-led', 'K1.1', 'Viernes', '07:45', '10:00'),
    ('isi-led', 'K1.2', 'Jueves', '07:45', '10:00'),
    ('isi-led', 'K1.2', 'Viernes', '10:10', '12:25'),
    ('isi-led', 'K1.3', 'Martes', '15:50', '18:05'),
    ('isi-led', 'K1.3', 'Jueves', '15:50', '18:05'),
    ('isi-led', 'K1.4', 'Lunes', '18:10', '20:25'),
    ('isi-led', 'K1.4', 'Viernes', '18:10', '20:25'),
    ('isi-led', 'K1.5', 'Martes', '15:50', '18:05'),
    ('isi-led', 'K1.5', 'Jueves', '15:50', '18:05'),
    ('isi-leg', 'K4.1', 'Lunes', '21:15', '22:45'),
    ('isi-leg', 'K4.1', 'Martes', '16:35', '18:05'),
    ('isi-pf', 'K5.1', 'Martes', '16:35', '18:55'),
    ('isi-pf', 'K5.1', 'Jueves', '16:35', '18:55'),
    ('isi-planif', 'K3.1', 'Lunes', '15:50', '18:05'),
    ('isi-planif', 'K3.1', 'Martes', '15:50', '18:05'),
    ('isi-ps', 'K5.1', 'Lunes', '15:50', '18:05'),
    ('isi-sg', 'K5.1', 'Lunes', '18:10', '20:25'),
    ('isi-sg', 'K5.1', 'Viernes', '16:35', '20:25'),
    ('isi-sim', 'K4.1', 'Lunes', '18:10', '20:25'),
    ('isi-sim', 'K4.1', 'Martes', '18:10', '20:25'),
    ('isi-sposn', 'K1.1', 'Lunes', '07:45', '10:00'),
    ('isi-sposn', 'K1.2', 'Martes', '07:45', '10:00'),
    ('isi-sposn', 'K1.3', 'Miércoles', '13:30', '15:45'),
    ('isi-sposn', 'K1.4', 'Miércoles', '20:30', '22:45'),
    ('isi-sposn', 'K1.5', 'Miércoles', '13:30', '15:45'),
    ('isi-ssi', 'K5.1', 'Martes', '18:55', '21:15'),
    ('isi-ssi', 'K5.1', 'Jueves', '18:55', '21:15'),
    ('isi-ssl', 'K2.1', 'Martes', '18:10', '19:40'),
    ('isi-ssl', 'K2.1', 'Miércoles', '13:30', '15:45'),
    ('isi-ssl', 'K2.1', 'Jueves', '15:50', '18:05'),
    ('isi-ssl', 'K2.2', 'Lunes', '17:20', '19:40'),
    ('isi-ssl', 'K2.2', 'Martes', '16:35', '18:05'),
    ('isi-ssl', 'K2.2', 'Jueves', '18:10', '20:25')
) as v(materia, comision, dia, hora_inicio, hora_fin)
join materia m on m.codigo = v.materia
join comision co on co.materia_id = m.id and co.codigo = v.comision
join dias d on d.nombre = v.dia
where not exists (select 1 from horario h where h.comision_id = co.id);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
delete from horario;
delete from comision;
alter table comision drop constraint if exists comision_unica;
alter table comision drop column if exists cuatrimestre;
update materia set programa = '';
delete from materia where codigo in ('isi-qca', 'isi-sdr', 'isi-ctda', 'isi-planif', 'isi-sgbd', 'isi-aacs', 'isi-agavz', 'isi-gis', 'isi-aaari', 'isi-ade', 'isi-aif', 'isi-devops', 'isi-fcs', 'isi-femp', 'isi-ps');
-- +goose StatementEnd
