server:
  port: 8080
  loglevel: INFO
  pool:
    max_open_conns: 25
    max_idle_conns: 5
    conn_max_lifetime: 30m
    conn_max_idletime: 5m

database:
  host: 127.0.0.1
  port: 5432
  user: chedul
  password: chedul
  name: chedul-db

JwtSecret: nEFOn1KDT5dtvT20yL2ZQNMywAE6LwEc2+KDBuYMY54=
